<?php
  // In the default installation, the language index = 2 is
  // represented as Slovak language.

  // $dictionary = [
  //   [$context, $originalString, $translatedString]
  // ];

  $dictionary = [
    ['WAI/Common/Navigation', 'Cart', 'Košík'],
    ['CartOverview', 'There are no more items in your cart', 'Váš košík je prázdny.'],
    ['BlogCatalog', 'Read more', 'Čítať viac'],
    ['WAI/Customer/Cart', 'Subtotal', 'Medzisúčet'],
    ['WAI/Customer/Cart', 'view cart', 'zobraziť košík'],
    ['WAI/Customer/Cart', 'checkout', 'kúpiť'],
    ['WAI/Customer/Cart', 'Continue shopping', 'Pokračovať v nákupe'],
    ['WAI/Common/Navigation', 'Subtotal', 'Medzisúčet'],
    ['WAI/Common/Navigation', 'view cart', 'zobraziť košík'],
    ['WAI/Common/Navigation', 'checkout', 'kúpiť'],
    ['WAI/Common/Navigation', 'Continue shopping', 'Pokračovať v nákupe'],
    ['WAI/Order/CartOverview', 'Your cart items', 'Váš košík'],
    ['WAI/Order/CartOverview', 'product', 'produkt'],
    ['WAI/Order/CartOverview', 'price', 'cena'],
    ['WAI/Order/CartOverview', 'unit', 'jednotka'],
    ['WAI/Order/CartOverview', 'pieces', 'kusov'],
    ['WAI/Order/CartOverview', 'unit', 'jednotka'],
    ['WAI/Order/CartOverview', 'price', 'cena'],
    ['WAI/Order/CartOverview', 'Clear Shopping Cart', 'Vyprádzniť košík'],
    ['WAI/Order/CartOverview', 'Cart Total', 'Spolu v košíku'],
    ['WAI/Order/CartOverview', 'Grand Total', 'Nákup spolu'],
    ['WAI/Order/CartOverview', 'Proceed to Checkout', 'Pokračovať k objednávke'],
    ['WAI/Order/CartOverview', 'There are no more items in your cart', 'Váš košík je prázdny'],
    ['WAI/Order/CartOverview', 'Continue shopping', 'Pokračovať v nákupe'],
    ['WAI/Order/Checkout', 'I have read the terms and conditions', 'Prečítal som si obchodné podmienky'],
    ['WAI/Order/Checkout', 'I agree to the processing of personal data for the processing of the order', 'Súhlasím so spracovaním osobných údajov pre účely spracovania objednávky'],
    ['WAI/Order/Checkout', 'I agree to the processing of personal data for the purpose of sending marketing information', 'Súhlasím so spracovaním osobných údajov pre marketingové účely'],
    ['Common', 'Surikata', 'Surikata'],
    ['Common', 'My account', 'Môj účet'],
    ['Common', 'Checkout', 'Košík'],
    ['Common', 'Logout', 'Odhlásiť sa'],
    ['Common', 'All categories', 'Všetky kategórie'],
    ['Common', 'Search', 'Hľadať'],
    ['Common', 'My Cart', 'Môj košík'],
    ['Common', 'Browse Categories', 'Prehľadávať kategórie'],
    ['Common', 'Enter your search key ...', 'Začnite vyhľadávať...'],
    ['Common', 'More Categories', 'Viac kategórií'],
    ['Common', 'Wishlist', 'Zoznam'],
    ['WAI/Common/Navigation', 'View wishlist', 'Zobraziť zoznam'],
    ['Common', 'Cart', 'Košík'],
    ['WAI/Common/Navigation', 'View cart', 'Zobraziť košík'],
    ['WAI/Common/Navigation', 'Checkout', 'Kúpiť'],
    ['Common', 'Search...', 'Hľadať...'],
    ['Common', 'Sign Up For Newsletters', 'Prihlásiť sa k odberu noviniek'],
    ['Common', "You'll be the first to know. Sign up for newsletter today!", 'Buďte stále v obraze. Prihláste sa k odberu noviniek ešte dnes!'],
    ['Common', 'Enter your email here', 'Zadajte Váš email'],
    ['Common', 'Sign Up', 'Prihlásiť sa'],
    ['Common', 'E-mail', 'E-mail'],
    ['Common', 'Phone', 'Telefón'],
    ['Common', 'Posted by', 'Publikoval'],
    ['WAI/Common/Footer', 'Copyright ©', 'Copyright ©'],
    ['Common', 'All Rights Reserved', 'Všetky práva vyhradené'],
    ['Common', 'Close', 'Zavrieť'],
    ['Common', 'Originals Kaval Windbr', ''],
    ['Common', 'Reference', 'Referencie'],
    ['Common', 'Read reviews', 'Recenzie'],
    ['Common', 'Lorem ipsum dolor sit amet, consectetur adipisic elit eiusm tempor incidid ut labore et dolore magna aliqua. Ut enim ad minim venialo quis nostrud exercitation ullamco', ''],
    ['Common', 'Add To Cart', 'Pridať do košíka'],
    ['Common', 'Add to wishlist', 'Pridať do zoznamu želení'],
    ['Common', 'Add to compare', 'Pridať do porovnania'],
    ['Common', 'Share', 'Zdieľať'],
    ['Common', 'Subscribe', 'Prihlásiť sa'],
    ['Common', 'Subscribe to the newsletter', 'Prihlásiť sa k odberu noviniek'],
    ['Common', 'Confirm', 'Potvrdiť'],
    ['Common', 'Cancel', 'Zrušiť'],
    ['Common', 'Don\'t show this popup again!', 'Nezobrazovať viac krát'],
    ['Misc', 'Shop now', 'Nakupujte teraz'],
    ['Product', 'Recommended products', 'Odporúčané produkty'],
    ['Product', 'Quick view', 'Rýchly náhľad'],
    ['Order', 'Do you already have an account?', 'Už ste registrovaný?'],
    ['Order', 'List of your adresses', 'Zoznam vašich adries'],
    ['Order', 'Billing Details', 'Fakturačné údaje'],
    ['Order', 'First Name', 'Krstné meno'],
    ['Order', 'Last Name', 'Priezvisko'],
    ['Order', 'Town / City', 'Obec'],
    ['Order', 'Postcode / ZIP', 'PSČ'],
    ['Order', 'Street Address', 'Ulica'],
    ['Order', 'House number and street name', 'Číslo domu'],
    ['Order', 'Apartment, suite, unit etc.', 'Byt...'],
    ['Order', 'Phone', 'Telefón'],
    ['Order', 'Email Address', 'Email'],
    ['Order', 'Buy as Company', 'Nakúpiť na firmu'],
    ['Order', 'Company Name', 'Názov firmy'],
    ['Order', 'Company ID', 'IČO'],
    ['Order', 'Company Tax ID', 'DIČ'],
    ['Order', 'Company Vat ID', 'IČ DPH'],
    ['Order', 'Additional information', 'Doplňujúce informácie'],
    ['Order', 'Order notes', 'Poznámky k objednávke'],
    ['Order', 'Notes about your order, e.g. special notes for delivery.', 'Poznámky k objednávke, napr. špeciálna poznámka pre doručenie'],
    ['Order', 'Ship to a different address?', 'Poslať na inú adresu?'],
    ['Order', 'I have read the terms and conditions', 'Prečítal som obchodné podmienky'],
    ['Order', 'I agree to the processing of personal data for the processing of the order', 'Súhlasím so spracovaním osobných údajov pre účely spracovania objednávky'],
    ['Order', 'I agree to the processing of personal data for the purpose of sending marketing information', 'Súhlasím so spracovaním osobných údajov pre marketingové účely'],
    ['Order', 'Shipping country', 'Cieľová krajina'],
    ['Order', 'Your order', 'Vaša objednávka'],
    ['Order', 'Product', 'Produkt'],
    ['Order', 'Total', 'Spolu'],
    ['Order', 'Shipping', 'Doprava'],
    ['Order', 'Payments', 'Platba'],
    ['Order', 'Place Order', 'Vytvoriť objednávku'],
    ['Order', 'There are no more items in your cart', 'Váš košík je prázdny.'],
    ['Order', 'Subtotal', 'Medzisúčet'],
    ['Product', 'Categories', 'Kategórie'],
    ['Product', 'Brand', 'Značka'],
    ['Product', 'Filter by', 'Filtrovať'],
    ['Product', 'Filter', 'Filter'],
    ['Product', 'There Are', 'Existujú'],
    ['Product', 'Products', 'Produkty'],
    ['Product', 'Number of displayed products', 'Počet zobrazených produktov'],
    ['Product', 'Sort by', 'Zoradiť'],
    ['Product', 'Sort by newness', 'Od najnovšieho'],
    ['Product', 'A to Z', 'od A do Z'],
    ['Product', 'Z to A', 'od Z do A'],
    ['Product', 'Price ascending', 'Ceny vzostupne'],
    ['Product', 'Price descending', 'Ceny zostupne'],
    ['Product', 'In stock', 'Na sklade'],
    ['Product', 'Add to Wishlist', 'Pridať do zoznamu želaní'],
    ['Product', 'Add to compare', 'Pridať do porovnania'],
    ['Product', 'Add to cart', 'Pridať do košíka'],
    ['Product', 'More products', 'Viac produktov'],
    ['WAI/Customer/Cart', 'View cart', 'Zobraziť košík'],
    ['WAI/Customer/Cart', 'Checkout', 'Objednávka'],
    ['Misc', 'Add to cart', 'Pridať do košíka'],
    ['Misc', 'Number of products in category', 'Počet produktov v kategórii'],
    ['WAI/Common/Navigation', 'Login', 'Prihlásiť sa'],
    ['Blog', 'Search entire store here ...', 'Prehľadávajte celý eshop tu...'],
    ['Blog', 'Archive', 'Archív'],
    ['Blog', 'Recent Posts', 'Posledné príspevky'],
    ['Blog', 'Tags', 'Tagy'],
    ['Blog', 'Read more', 'Čítať viac'],
    ['Order', 'Your cart items', 'Položky vo Vašom košíku'],
    ['Order', 'Price', 'Cena'],
    ['Order', 'Unit', 'Jednotka'],
    ['Order', 'Pieces', 'Kusy'],
    ['Order', 'Clear Shopping Cart', 'Vymazať všetky položky z košíka'],
    ['Order', 'Cart Total', 'Spolu v košíku'],
    ['Order', 'Grand Total', 'Spolu'],
    ['Order', 'Proceed to Checkout', 'Pokračovať v objednávke'],
    ['Blog', 'Share', 'Zdieľať'],
    ['Product', 'New', 'Novinka'],
    ['Product', 'Top', 'Top'],
    ['Product', 'The product has been added to the cart.', 'Produkt bol pridaný do košíka'],
    ['Product', 'Go to order', 'Pokračovať k objednávke'],
    ['Product', 'Continue shopping', 'Pokračovať v nákupe'],
    ['Product', 'Add To Cart', 'Pridať do košíka'],
    ['Product', 'Description', 'Popis'],
    ['Product', 'Product Details', 'Detaily produktu'],
    ['Product', 'White Lewis', ''],
    ['Product', 'Reply', 'Odpovedať'],
    ['Product', 'Vestibulum ante ipsum primis aucibus orci luctustrices posuere cubilia Curae Suspendisse viverra ed viverra. Mauris ullarper euismod vehicula. Phasellus quam nisi, congue id nulla.', ''],
    ['Product', 'Vestibulum ante ipsum primis aucibus orci luctustrices posuere cubilia Curae Sus pen disse viverra ed viverra. Mauris ullarper euismod vehicula.', ''],
    ['Product', 'Add a Review', 'Pridať recenziu'],
    ['Product', 'Your rating', 'Vaše hodnotenie'],
    ['Product', 'Name', 'Meno'],
    ['Product', 'Email', 'Email'],
    ['Product', 'Message', 'Správa'],
    ['Product', 'Submit', 'Poslať'],
    ['Product', 'Accessories', 'Príslušenstvo'],
    ['Product', 'Similar products', 'Podobné produkty'],
    ['Product', 'Action', 'Akcia'],
    ['Product', 'Availability', 'Dostupnosť'],
    ['Product', 'Filter By', 'Filter'],
    ['Product', 'Color', 'Farba'],
    ['Order', 'Thank you for your order. We sent the recapitulation and confirmation to the email.', 'Ďakujeme za Vašu objednávku. Poslali sme vám rekapituláciu a potvrdenie na email.'],
    ['Order', 'Order ID', 'Vaše ID'],
    ['Order', 'Order number', 'Číslo objednávky'],
    ['Order', 'You will be redirected to the payment gateway', 'Budete presmerovaný na platobnú bránu'],
    ['Order', 'Continue shopping', 'Pokračovať v nákupe'],
    ['Customer', 'Login', 'Prihláste sa'],
    ['Customer', 'Register', 'Registrujte sa'],
    ['Customer', 'Failed to login', 'Nepodarilo sa prihlásiť'],
    ['Customer', 'E-mail', 'E-mail'],
    ['Customer', 'Password', 'Heslo'],
    ['Customer', 'Remember me', 'Zapamätať prihlásenie'],
    ['Customer', 'Forgot password', 'Zabudli ste heslo'],
    ['Customer', 'Email is incomplete or invalid.', 'Email je v nesprávnom formáte'],
    ['Customer', 'Such an account already exists.', 'Tento email už je registrovaný'],
    ['Customer', 'An unexpected error occurred while creating the account. Please try again later.', 'Nastala neočakávaná chyba pri vytváraní účtu. Skúste znova neskôr.'],
    ['Customer', 'Retype Password', 'Zopakujte heslo'],
    ['Customer', 'I agree with the processing of personal data.', 'Súhlasím so spracovaním osobných údajov'],
    ['Customer', 'You must agree to the terms of processing of personal data.', 'Musíte súhlasiť s podmienkami spracovania osobných údajov.'],
    ['Customer', 'Show conditions', 'Ukáž podmienky'],
    ['Customer', 'Your account has been successfully verified.', 'Váš účet bol úspešne overený.'],
    ['Customer', 'Now you can sing in here', 'Teraz sa môžete prihlásiť'],
    ['Customer', 'Your account has been successfully created. We`ve sent a link to your email address', 'Váš účet bol úspešne vytvorený. Na vašu emailovú adresu'],
    ['Customer', 'to verify your account. Please verify your account before logging in for the first time.', 'sme poslali odkaz na overenie vášho účtu. Prosím overte vašu emailovú adresu pred prvým prihlásením.'],
    ['Customer', 'Thank you for your trust.', 'Ďakujeme Vám za vašu dôveru.'],
    ['Customer', 'Invalid link for email confirmation', 'Neplatný odkaz pre overenie emailu.'],
    ['Cookies', 'Privacy Settings', 'Súhlas s používaním cookies'],
    ['Cookies', 'Privacy content', 'Tieto internetové stránky používajú k poskytovaniu služieb, personalizácií reklám a analýze návštevnosti súbory cookie.'],
    ['Cookies', 'More information', 'Ďalšie informácie'],
    ['Cookies', 'My settings', 'Moje nastavenia'],
    ['Cookies', 'Necessary', 'Potrebné'],
    ['Cookies', 'Required to run the website', 'Cookies potrebné pre plnú funkčnosť Surikata Online Eshopu'],
    ['Cookies', 'Analyses', 'Analytické'],
    ['Cookies', 'Monitoring website usage and optimizing the user experience', 'Monitorujú používanie Eshopu a optimalizujú používateľské rozhranie'],
    ['Cookies', 'Evaluation of marketing actions', 'Vyhodnocujú marketingové akcie'],
    ['Cookies', 'Personalization', 'Personalizované'],
    ['Cookies', 'Storage of your preferences from previous visits', 'Ukladajú Vaše nastavenia z predchádzajúcich návštev webu'],
    ['Cookies', 'Collecting user feedback to improve our website', 'Zbierajú údaje používateľ kvôli zlepšeniu Eshopu'],
    ['Cookies', 'Recording of your interests in order to provide customised content and offers', 'Zaznamenávajú vaše záujmy za účelom poskytovania prispôsobeného obsahu a ponúk'],
    ['Cookies', 'I do not agree', 'Nesúhlasím'],
    ['Cookies', 'Agree', 'Súhlasím'],
    ['Cookies', 'Save selection', 'Uložiť nastavenia'],
    ['Cookies', 'Agree to all', 'Súhlasím so všetkými Cookies'],
    ['Order', 'Do you already have an account?', 'Máte už u nás účet?'],
    ['Order', 'Login', 'Prihlásiť sa'],
    ['WAI/Proprietary/Product/Compare', 'Product was added to comparison.', 'Produkt bol pridaný do porovnania.'],
    ['WAI/Proprietary/Delivery/Packeta', 'Select pick-up point', 'Vyberte miesto vyzdvihnutia'],
    ['Order', 'Discount', 'Zľava'],
    ['Order', 'Grand total with discount', 'Spolu so zľavou'],
    ['Order', 'Subtotal with discount', 'Medzisúčet so zľavou'],
    ['Order', 'Total with discount', 'Spolu so zľavou'],
  ];